version: "3.8"
services:
  app-be:
    build: .
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - INTERVAL=production
    command: npm start
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
